/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyTask {
  'isCompleted' : boolean,
  'taskType' : DailyTaskType,
}
export type DailyTaskType = { 'solve_two_puzzles' : null } |
  { 'solve_no_hints' : null } |
  { 'solve_under_time' : null };
export type Difficulty = { 'easy' : null } |
  { 'hard' : null } |
  { 'master' : null } |
  { 'expert' : null } |
  { 'medium' : null };
export interface PlayerProfile {
  'xp' : bigint,
  'dailyTasks' : Array<DailyTask>,
  'weeklyChallenge' : WeeklyChallenge,
  'puzzlesSolved' : bigint,
  'badges' : Array<string>,
  'rank' : bigint,
  'errorsMade' : bigint,
  'uuid' : string,
  'dailyTasksTimestamp' : bigint,
  'stats' : PlayerStats,
  'hintsUsed' : bigint,
}
export interface PlayerStats {
  'avgMasterTime' : bigint,
  'avgExpertTime' : bigint,
  'avgEasyTime' : bigint,
  'avgHardTime' : bigint,
  'avgMediumTime' : bigint,
}
export interface WeeklyChallenge {
  'puzzlesCompleted' : bigint,
  'weekStartTimestamp' : bigint,
  'badgeAwarded' : boolean,
}
export interface _SERVICE {
  'getAllPlayerProfiles' : ActorMethod<[], Array<PlayerProfile>>,
  'getPlayerData' : ActorMethod<[string], PlayerProfile>,
  'initializePlayer' : ActorMethod<[string], PlayerProfile>,
  'recordPuzzleSolve' : ActorMethod<
    [string, Difficulty, bigint, bigint, bigint],
    { 'newXp' : bigint, 'badgeUnlocked' : boolean, 'newRank' : bigint }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];