/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DailyTaskType = IDL.Variant({
  'solve_two_puzzles' : IDL.Null,
  'solve_no_hints' : IDL.Null,
  'solve_under_time' : IDL.Null,
});
export const DailyTask = IDL.Record({
  'isCompleted' : IDL.Bool,
  'taskType' : DailyTaskType,
});
export const WeeklyChallenge = IDL.Record({
  'puzzlesCompleted' : IDL.Nat,
  'weekStartTimestamp' : IDL.Int,
  'badgeAwarded' : IDL.Bool,
});
export const PlayerStats = IDL.Record({
  'avgMasterTime' : IDL.Nat,
  'avgExpertTime' : IDL.Nat,
  'avgEasyTime' : IDL.Nat,
  'avgHardTime' : IDL.Nat,
  'avgMediumTime' : IDL.Nat,
});
export const PlayerProfile = IDL.Record({
  'xp' : IDL.Nat,
  'dailyTasks' : IDL.Vec(DailyTask),
  'weeklyChallenge' : WeeklyChallenge,
  'puzzlesSolved' : IDL.Nat,
  'badges' : IDL.Vec(IDL.Text),
  'rank' : IDL.Nat,
  'errorsMade' : IDL.Nat,
  'uuid' : IDL.Text,
  'dailyTasksTimestamp' : IDL.Int,
  'stats' : PlayerStats,
  'hintsUsed' : IDL.Nat,
});
export const Difficulty = IDL.Variant({
  'easy' : IDL.Null,
  'hard' : IDL.Null,
  'master' : IDL.Null,
  'expert' : IDL.Null,
  'medium' : IDL.Null,
});

export const idlService = IDL.Service({
  'getAllPlayerProfiles' : IDL.Func([], [IDL.Vec(PlayerProfile)], ['query']),
  'getPlayerData' : IDL.Func([IDL.Text], [PlayerProfile], ['query']),
  'initializePlayer' : IDL.Func([IDL.Text], [PlayerProfile], []),
  'recordPuzzleSolve' : IDL.Func(
      [IDL.Text, Difficulty, IDL.Nat, IDL.Nat, IDL.Nat],
      [
        IDL.Record({
          'newXp' : IDL.Nat,
          'badgeUnlocked' : IDL.Bool,
          'newRank' : IDL.Nat,
        }),
      ],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DailyTaskType = IDL.Variant({
    'solve_two_puzzles' : IDL.Null,
    'solve_no_hints' : IDL.Null,
    'solve_under_time' : IDL.Null,
  });
  const DailyTask = IDL.Record({
    'isCompleted' : IDL.Bool,
    'taskType' : DailyTaskType,
  });
  const WeeklyChallenge = IDL.Record({
    'puzzlesCompleted' : IDL.Nat,
    'weekStartTimestamp' : IDL.Int,
    'badgeAwarded' : IDL.Bool,
  });
  const PlayerStats = IDL.Record({
    'avgMasterTime' : IDL.Nat,
    'avgExpertTime' : IDL.Nat,
    'avgEasyTime' : IDL.Nat,
    'avgHardTime' : IDL.Nat,
    'avgMediumTime' : IDL.Nat,
  });
  const PlayerProfile = IDL.Record({
    'xp' : IDL.Nat,
    'dailyTasks' : IDL.Vec(DailyTask),
    'weeklyChallenge' : WeeklyChallenge,
    'puzzlesSolved' : IDL.Nat,
    'badges' : IDL.Vec(IDL.Text),
    'rank' : IDL.Nat,
    'errorsMade' : IDL.Nat,
    'uuid' : IDL.Text,
    'dailyTasksTimestamp' : IDL.Int,
    'stats' : PlayerStats,
    'hintsUsed' : IDL.Nat,
  });
  const Difficulty = IDL.Variant({
    'easy' : IDL.Null,
    'hard' : IDL.Null,
    'master' : IDL.Null,
    'expert' : IDL.Null,
    'medium' : IDL.Null,
  });
  
  return IDL.Service({
    'getAllPlayerProfiles' : IDL.Func([], [IDL.Vec(PlayerProfile)], ['query']),
    'getPlayerData' : IDL.Func([IDL.Text], [PlayerProfile], ['query']),
    'initializePlayer' : IDL.Func([IDL.Text], [PlayerProfile], []),
    'recordPuzzleSolve' : IDL.Func(
        [IDL.Text, Difficulty, IDL.Nat, IDL.Nat, IDL.Nat],
        [
          IDL.Record({
            'newXp' : IDL.Nat,
            'badgeUnlocked' : IDL.Bool,
            'newRank' : IDL.Nat,
          }),
        ],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };