/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface WeeklyChallenge {
    puzzlesCompleted: bigint;
    weekStartTimestamp: bigint;
    badgeAwarded: boolean;
}
export interface DailyTask {
    isCompleted: boolean;
    taskType: DailyTaskType;
}
export interface PlayerStats {
    mediumCount: bigint;
    avgMasterTime: bigint;
    masterCount: bigint;
    avgExpertTime: bigint;
    avgEasyTime: bigint;
    avgHardTime: bigint;
    expertCount: bigint;
    hardCount: bigint;
    avgMediumTime: bigint;
    easyCount: bigint;
}
export interface PlayerProfile {
    xp: bigint;
    dailyTasks: Array<DailyTask>;
    weeklyChallenge: WeeklyChallenge;
    puzzlesSolved: bigint;
    badges: Array<string>;
    rank: bigint;
    errorsMade: bigint;
    uuid: string;
    dailyTasksTimestamp: bigint;
    stats: PlayerStats;
    hintsUsed: bigint;
}
export enum DailyTaskType {
    solve_two_puzzles = "solve_two_puzzles",
    solve_no_hints = "solve_no_hints",
    solve_under_time = "solve_under_time"
}
export enum Difficulty {
    easy = "easy",
    hard = "hard",
    master = "master",
    expert = "expert",
    medium = "medium"
}
export interface backendInterface {
    addStreakBonus(uuid: string, bonusXp: bigint): Promise<bigint>;
    getAllPlayerProfiles(): Promise<Array<PlayerProfile>>;
    getPlayerData(uuid: string): Promise<PlayerProfile>;
    initializePlayer(uuid: string): Promise<PlayerProfile>;
    recordPuzzleSolve(uuid: string, difficulty: Difficulty, solveTime: bigint, hintsUsed: bigint, errorsMade: bigint): Promise<{
        unlockedBadges: Array<string>;
        newXp: bigint;
        badgeUnlocked: boolean;
        newRank: bigint;
    }>;
}
import type { DailyTask as _DailyTask, DailyTaskType as _DailyTaskType, Difficulty as _Difficulty, PlayerProfile as _PlayerProfile, PlayerStats as _PlayerStats, WeeklyChallenge as _WeeklyChallenge } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addStreakBonus(arg0: string, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addStreakBonus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStreakBonus(arg0, arg1);
            return result;
        }
    }
    async getAllPlayerProfiles(): Promise<Array<PlayerProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPlayerProfiles();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPlayerProfiles();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayerData(arg0: string): Promise<PlayerProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerData(arg0);
                return from_candid_PlayerProfile_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerData(arg0);
            return from_candid_PlayerProfile_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializePlayer(arg0: string): Promise<PlayerProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.initializePlayer(arg0);
                return from_candid_PlayerProfile_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializePlayer(arg0);
            return from_candid_PlayerProfile_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordPuzzleSolve(arg0: string, arg1: Difficulty, arg2: bigint, arg3: bigint, arg4: bigint): Promise<{
        unlockedBadges: Array<string>;
        newXp: bigint;
        badgeUnlocked: boolean;
        newRank: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.recordPuzzleSolve(arg0, to_candid_Difficulty_n9(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordPuzzleSolve(arg0, to_candid_Difficulty_n9(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
            return result;
        }
    }
}
function from_candid_DailyTaskType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DailyTaskType): DailyTaskType {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_DailyTask_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DailyTask): DailyTask {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_PlayerProfile_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayerProfile): PlayerProfile {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    xp: bigint;
    dailyTasks: Array<_DailyTask>;
    weeklyChallenge: _WeeklyChallenge;
    puzzlesSolved: bigint;
    badges: Array<string>;
    rank: bigint;
    errorsMade: bigint;
    uuid: string;
    dailyTasksTimestamp: bigint;
    stats: _PlayerStats;
    hintsUsed: bigint;
}): {
    xp: bigint;
    dailyTasks: Array<DailyTask>;
    weeklyChallenge: WeeklyChallenge;
    puzzlesSolved: bigint;
    badges: Array<string>;
    rank: bigint;
    errorsMade: bigint;
    uuid: string;
    dailyTasksTimestamp: bigint;
    stats: PlayerStats;
    hintsUsed: bigint;
} {
    return {
        xp: value.xp,
        dailyTasks: from_candid_vec_n4(_uploadFile, _downloadFile, value.dailyTasks),
        weeklyChallenge: value.weeklyChallenge,
        puzzlesSolved: value.puzzlesSolved,
        badges: value.badges,
        rank: value.rank,
        errorsMade: value.errorsMade,
        uuid: value.uuid,
        dailyTasksTimestamp: value.dailyTasksTimestamp,
        stats: value.stats,
        hintsUsed: value.hintsUsed
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isCompleted: boolean;
    taskType: _DailyTaskType;
}): {
    isCompleted: boolean;
    taskType: DailyTaskType;
} {
    return {
        isCompleted: value.isCompleted,
        taskType: from_candid_DailyTaskType_n7(_uploadFile, _downloadFile, value.taskType)
    };
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    solve_two_puzzles: null;
} | {
    solve_no_hints: null;
} | {
    solve_under_time: null;
}): DailyTaskType {
    return "solve_two_puzzles" in value ? DailyTaskType.solve_two_puzzles : "solve_no_hints" in value ? DailyTaskType.solve_no_hints : "solve_under_time" in value ? DailyTaskType.solve_under_time : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PlayerProfile>): Array<PlayerProfile> {
    return value.map((x)=>from_candid_PlayerProfile_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DailyTask>): Array<DailyTask> {
    return value.map((x)=>from_candid_DailyTask_n5(_uploadFile, _downloadFile, x));
}
function to_candid_Difficulty_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): _Difficulty {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): {
    easy: null;
} | {
    hard: null;
} | {
    master: null;
} | {
    expert: null;
} | {
    medium: null;
} {
    return value == Difficulty.easy ? {
        easy: null
    } : value == Difficulty.hard ? {
        hard: null
    } : value == Difficulty.master ? {
        master: null
    } : value == Difficulty.expert ? {
        expert: null
    } : value == Difficulty.medium ? {
        medium: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
